--- #YAML:1.0
name:                Alter
version:             0.02
abstract:            I<Alter Ego> Objects
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Anno Siegel <anno@zrz.tu-berlin.de>
